name: WebdriverTest

on:
  push:
    branches:
    - master  
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build dockerfile and run dockerfile
      run: |
       docker build . -t cypress-docker-app:v1
       docker run -d -p 8001:8040 cypress-docker-app:v1

    - name: Start containers
      run: docker-compose -f "selenium-4-grid.yml" up -d --build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cypress-docker-app:v1

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: Url=PROD_URL npm run testchrome 

    - name: Stop dockerfile 
      run: docker stop vladocker1qa2/node-docker-app:v1
  
    - name: Stop containers
      if: always()
      run: docker-compose -f "selenium-4-grid.yml" down
    
    
    
    - name: Deploy 🚀
      if: always()
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: allure-report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
